export { About } from "./About";
export { Hero } from "./Hero";
export { Service } from "./Service";
export { Animation } from "./Animation";
export { Solution } from "./Solution";
export { Vision } from "./Vision";
export { Clients } from "./Clients";
export { Footer } from "./Footer";
export { Contact } from "./Contact";